export const data = [
  {
    id: 1,
    name: "Egypt",
    price: 120,
    image: "/src/assets/1.jpeg",
    rate: 4.95,
    description: "New Hotel In Egypt By Damas",
  },
  {
    id: 2,
    name: "Alex",
    price: 420,
    image: "/src/assets/2.avif",
    rate: 4.55,
    description: "Its Camp In Alex Show The Sea",
  },
  {
    id: 3,
    name: "maady",
    price: 220,
    image: "/src/assets/3.avif",
    rate: 4.95,
    description: "New Hotel In Maady By Damas",
  },
  {
    id: 4,
    name: "Dahab",
    price: 1200,
    image: "/src/assets/4.avif",
    rate: 4.95,
    description: "Charming hotel apartments by the beach",
  },
  {
    id: 5,
    name: "Dahab",
    price: 420,
    image: "/src/assets/5.avif",
    rate: 4.55,
    description: "Its Camp In Alex Show The Sea",
  },
  {
    id: 6,
    name: "Dahab",
    price: 250,
    image: "/src/assets/6.avif",
    rate: 4.33,
    description: "Affordable comfort in central city location",
  },
  {
    id: 7,
    name: "Dahab",
    price: 300,
    image: "/src/assets/7.avif",
    rate: 4.05,
    description: "Relaxing suites with private pool access",
  },
  {
    id: 8,
    name: "Alex",
    price: 420,
    image: "/src/assets/8.avif",
    rate: 4.55,
    description: "Its Camp In Alex Show The Sea",
  },
  {
    id: 9,
    name: "Hurghada",
    price: 360,
    image: "/src/assets/9.avif",
    rate: 4.56,
    description: "Stylish apartments overlooking the Nile River",
  },

  {
    id: 10,
    name: "Alex",
    price: 420,
    image: "/src/assets/10.webp",
    rate: 4.55,
    description: "Its Camp In Alex Show The Sea",
  },
  {
    id: 11,
    name: "nasrCity",
    price: 3020,
    image: "/src/assets/11.avif",
    rate: 4.98,
    description: "Comfortable stay with premium hotel services",
  },
  {
    id: 11,
    name: "nasrCity",
    price: 420,
    image: "/src/assets/12.avif",
    rate: 4.55,
    description: "Its Camp In Alex Show The Sea",
  },
  {
    id: 13,
    name: "nasrCity",
    price: 2200,
    image: "/src/assets/13.avif",
    rate: 4.0,
    description: "Modern furnished apartments near the sea",
  },
  {
    id: 14,
    name: "Alex",
    price: 80,
    image: "/src/assets/14.avif",
    rate: 3.55,
    description: "Elegant suites in the heart of Egypt",
  },
  {
    id: 15,
    name: "nasrCity",
    price: 350,
    image: "/src/assets/15.avif",
    rate: 4.15,
    description: "Luxury hotel apartments with stunning views",
  },
];
